added new tests in agent_test.go
step-security/agent pull request #143
Opened 2022-01-07 06:21 UTC by h0x0er

#### added test functions for:
* writeDone()
* writeStatus()

#### added a new test_case in TestRun function that triggers a specific block of code in agent.go; requiring the command arg to be nil.

![agent_test_](https://user-images.githubusercontent.com/84621253/148500960-4b6d52d2-60b1-473e-bed9-003e52c52c76.png)

2022-01-08 01:06 UTC, varunsh-coder requested changes

2022-01-18 22:24 UTC, varunsh-coder commented
@h0x0er I think we discussed this offline. Please let me know if anything pending on my side.

2022-01-21 03:33 UTC, varunsh-coder commented on agent.go
> +		_ = writeStatus(fmt.Sprintf("Error reading config file %v", err))
@h0x0er you can remove the `_ =` part. That is redundant. Same applies to other places as well.

2022-01-21 03:34 UTC, varunsh-coder commented
@h0x0er once you make the changes, please create a PR into `rcbranch`. I will then merge changes into `int` to do integration testing.

2022-01-21 05:52 UTC, h0x0er commented
@varunsh-coder I am closing this PR and creating a new one into `rcbranch`

2022-01-21 05:52 UTC, closed without merging